# Generated by Django 3.0.5 on 2020-04-19 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0002_auto_20200419_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
    ]
