# Generated by Django 3.0.6 on 2020-05-17 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0007_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
